### PR TITLE
cleaning the existing CheckHitsAndTracks module (ProtoDUNE-VD)

### PR DESCRIPTION
**Pull request by woohoudy**
Moving the outcomes to fLogLevel conditions and structuring better the functionalities of the module.

### CODE REVIEW

**Comment by calcuttj** [comment]
trigger build

**Comment by woohoudy** [comment]
@calcuttj Hey Jake, the CLANG warning are now solved. Can you review again please? Cheers

**Comment by calcuttj** [comment]
trigger build

**Comment by calcuttj** [comment]
trigger build with DUNE/dunecore#63

**Review by calcuttj — APPROVED** [review]

**Pull request merged**
